### ISSUE TITLE
addBoard에서 spinner 오류 확인

### ISSUE THREAD

**Issue by HongEunbeen** [mirimitshow/Scan_Class_Android#72]
addBoard에서 spinner 오류

**Comment by HongEunbeen** [comment]
@tmddus

데이터는 들어오는데 선택 오류!

**Comment by HongEunbeen** [comment]
@tmddus 

ScanActivity에서도 spinner 오류! 같은 오류 인듯

**Comment by tmddus** [comment]
addBoardActivity에 token이라는 String 변수에 Spinner로 선택된 그룹 이름 넣어놓았습니당,,,,,,,,,,,
.
.
Scan은 아직 고치는 즁이에용,,,,
ㅎㅎ
ㅎ

**Comment by tmddus** [comment]
ScanClassActivity내의 getCategory 메소드 에서 user.getCategoty가 null로 리턴됩니다,,,,,,, 카테고리 목록이 없어서 스피너에 들어갈 값이 없어용

**Comment by tmddus** [comment]
ViewBoard두 비슷한 상태입니다,, ,,, 파일을 잘못 합쳤나,,?

**Comment by HongEunbeen** [comment]
0609 오류 확인 수정 완료 테스트 완료
