### ISSUE TITLE
Group1Fragment 게시물 목록 오류 확인

### ISSUE THREAD

**Issue by tmddus** [mirimitshow/Scan_Class_Android#74]
게시물을 작성해도 아무것도 뜨지 않습니다,,. 그래서 이미지가 어떻게 깨지는지도 확인할 수가 없어요 ㅜㅜ

확인하고 연락주세요, . .. 

@HongEunbeen

**Comment by HongEunbeen** [comment]
fragment에러 확인 -> 생명 주기 에러!

**Comment by HongEunbeen** [comment]
0609 오류 확인 테스트 완료
