### ISSUE TITLE
scan_sub listview 오류 

### ISSUE THREAD

**Issue by HongEunbeen** [mirimitshow/Scan_Class_Android#79]
@tmddus 
승연아 이거 adapter로 string말고 scan 객체 받아야 해ㅠ 
그리고 그냥 recyclerview로 하는게 좋을 듯!

**Comment by tmddus** [comment]
변경 다 해놓았는데 이번엔 스캔이 안돼서 테스트 못해봣스미다,, , , 내 파일이 또 이상한가, , , ,?
